import Head from "next/head";
import Home from "./Home";
import cowsay from "cowsay";
import chalk from "chalk";

export default function Root() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        console.log(cowsay.say({text: "Hello, I'm a self-aught polyglot and a aspiring programmer"}));
      </div>
    </>
  );
}